<?php

declare(strict_types=1);

namespace Catalyst\Framework\Module;

use Catalyst\Framework\Cli\ScaffoldManager;
use RuntimeException;

final class ModuleBlueprintFactory
{
    private const SURFACES = [
        'none',
        'public',
        'workspace',
        'administration',
        'devtools',
    ];

    public function __construct(
        private readonly ScaffoldManager $manager,
        private readonly ModuleManifestBuilder $manifestBuilder,
        private readonly ModuleFileFactory $fileFactory
    ) {
    }

    /**
     * @param array<string, mixed> $input
     * @return array<string, mixed>
     */
    public function build(array $input): array
    {
        $module = $this->manager->normalizeModuleName((string) ($input['module'] ?? $input['name'] ?? ''));
        $space = $this->manager->normalizeSpace((string) ($input['space'] ?? 'App'));
        $rawSurface = trim((string) ($input['surface'] ?? ''));
        $surface = $this->normalizeSurface($rawSurface !== '' ? $rawSurface : ($space === 'App' ? 'public' : 'none'));
        $description = $this->normalizeDescription((string) ($input['description'] ?? ''), $module);
        $permissionSlug = $this->normalizePermissionSlug((string) ($input['permission_slug'] ?? $input['permission'] ?? ''));
        $this->assertPermissionSurfaceCompatibility($surface, $permissionSlug);
        $settings = $this->normalizeList($input['settings'] ?? []);
        $featureFlags = $this->normalizeList($input['feature_flags'] ?? $input['featureFlags'] ?? []);

        $baseDir = $this->manager->moduleBaseDirectory($space, $module);
        $namespaceRoot = $this->manager->moduleNamespaceRoot($space, $module);
        $viewNamespace = $this->manager->moduleViewNamespace($module);
        $routeUri = $this->manager->moduleRouteUri($module);
        $controllerName = $module . 'Controller';
        $layout = in_array($surface, ['workspace', 'administration', 'devtools'], true) ? 'admin' : null;
        $manifest = $this->manifestBuilder->build(
            $module,
            $routeUri,
            $surface,
            $description,
            $permissionSlug,
            $settings,
            $featureFlags
        );

        $blueprint = [
            'module' => $module,
            'space' => $space,
            'surface' => $surface,
            'description' => $description,
            'permission_slug' => $permissionSlug,
            'settings' => $settings,
            'feature_flags' => $featureFlags,
            'base_dir' => $baseDir,
            'namespace_root' => $namespaceRoot,
            'view_namespace' => $viewNamespace,
            'route_uri' => $routeUri,
            'controller_name' => $controllerName,
            'layout' => $layout,
            'manifest' => $manifest,
            'manifest_contents' => $this->manifestBuilder->render($manifest),
            'exists' => is_dir($baseDir),
        ];

        $blueprint['files'] = $this->fileFactory->build($blueprint);

        return $blueprint;
    }

    private function normalizeSurface(string $surface): string
    {
        $surface = strtolower(trim($surface));

        if (!in_array($surface, self::SURFACES, true)) {
            throw new RuntimeException(
                'The surface must be one of: ' . implode(', ', self::SURFACES) . '.'
            );
        }

        return $surface;
    }

    private function normalizeDescription(string $description, string $module): string
    {
        $description = trim($description);

        return $description !== ''
            ? $description
            : sprintf('%s module scaffold generated by Catalyst tooling.', $module);
    }

    /**
     * @param mixed $value
     * @return string[]
     */
    private function normalizeList(mixed $value): array
    {
        if (is_array($value)) {
            $items = $value;
        } else {
            $items = preg_split('/[\r\n,]+/', (string) $value) ?: [];
        }

        $items = array_map(
            static fn (mixed $item): string => trim((string) $item),
            $items
        );
        $items = array_values(array_filter($items, static fn (string $item): bool => $item !== ''));
        $items = array_values(array_unique($items));
        sort($items);

        return $items;
    }

    private function normalizePermissionSlug(string $slug): string
    {
        $slug = trim(strtolower($slug));

        if ($slug === '') {
            return '';
        }

        if (preg_match('/^[a-z0-9]+(?:-[a-z0-9]+)*$/', $slug) !== 1) {
            throw new RuntimeException('The permission slug must be lowercase kebab-case.');
        }

        return $slug;
    }

    private function assertPermissionSurfaceCompatibility(string $surface, string $permissionSlug): void
    {
        if ($permissionSlug === '') {
            return;
        }

        if (in_array($surface, ['none', 'public'], true)) {
            throw new RuntimeException(
                'Permission slug requires a guarded surface: workspace, administration or devtools.'
            );
        }
    }
}
