<?php

declare(strict_types=1);

/**
 * Catalyst PHP Framework
 *
 * A modern PHP 8.4 framework for building
 * robust and scalable web applications.
 *
 * PHP Version 8.4 (Required).
 *
 * @package    Catalyst
 *
 * @author     Walter Nuñez (arcanisgk/original founder)
 * @email      <wnunez@lh-2.net>
 * @email      <icarosnet@gmail.com>
 * @copyright  2024-2026 Walter Francisco Nuñez Cruz and Icaros Net
 * @license    Proprietary - https://catalyst.lh-2.net/license
 *
 * @version    GIT: See repository tags
 *
 * @category   Framework
 * @filesource
 *
 * @link       https://catalyst.lh-2.net Project homepage
 * @see        https://catalyst.lh-2.net/docs Documentation
 *
 */

namespace Catalyst\Framework\Auth;

use Catalyst\Helpers\Config\ConfigManager;

/**
 * AuthInputGuard centralizes small security checks shared by public auth flows.
 */
final class AuthInputGuard
{
    /** Raw email/password tokens are generated by bin2hex(random_bytes(32)). */
    private const RAW_TOKEN_PATTERN = '/\A[a-f0-9]{64}\z/i';

    /** TOTP is 6 digits; backup codes are XXXX-XXXX or XXXXXXXX hexadecimal. */
    private const MFA_CODE_PATTERN = '/\A(?:\d{6}|[A-F0-9]{4}-?[A-F0-9]{4})\z/i';

    /**
     * Return a safe local redirect target. External URLs, protocol-relative URLs,
     * control characters and backslash-based browser ambiguities fall back safely.
     */
    public static function localRedirect(?string $target, string $fallback = '/'): string
    {
        $target = trim((string) $target);
        $fallback = self::fallbackPath($fallback);

        if ($target === '') {
            return $fallback;
        }

        $decoded = rawurldecode($target);

        if (
            $target[0] !== '/'
            || str_starts_with($target, '//')
            || str_contains($target, '\\')
            || str_contains($decoded, '\\')
            || preg_match('/[\x00-\x1F\x7F]/', $target) === 1
            || preg_match('/[\x00-\x1F\x7F]/', $decoded) === 1
            || preg_match('/^[a-z][a-z0-9+.-]*:/i', $decoded) === 1
            || str_starts_with($decoded, '//')
        ) {
            return $fallback;
        }

        return $target;
    }

    /**
     * Determines whether is Raw Token.
     */
    public static function isRawToken(string $token): bool
    {
        return preg_match(self::RAW_TOKEN_PATTERN, trim($token)) === 1;
    }

    /**
     * Normalizes the provided value.
     */
    public static function normalizeMfaCode(string $code): string
    {
        return strtoupper(trim($code));
    }

    /**
     * Determines whether is Mfa Code Candidate.
     */
    public static function isMfaCodeCandidate(string $code): bool
    {
        return preg_match(self::MFA_CODE_PATTERN, self::normalizeMfaCode($code)) === 1;
    }

    /**
     * Password policy is intentionally backwards-compatible: defaults mirror the
     * existing min:8 behavior unless security.json opts into stricter flags.
     *
     * Supported config path:
     * security.security.password_policy = {
     *   "min_length": 8,
     *   "require_uppercase": false,
     *   "require_number": false,
     *   "require_symbol": false
     * }
     *
     * @return array{minLength:int,requireUppercase:bool,requireNumber:bool,requireSymbol:bool}
     */
    public static function passwordPolicy(): array
    {
        $policy = [];

        try {
            $configured = ConfigManager::getInstance()->get('security.security.password_policy', []);
            if (is_array($configured)) {
                $policy = $configured;
            }
        } catch (\Throwable) {
            $policy = [];
        }

        return [
            'minLength' => max(8, min(128, (int) ($policy['min_length'] ?? $policy['minLength'] ?? 8))),
            'requireUppercase' => self::boolean($policy['require_uppercase'] ?? $policy['requireUppercase'] ?? false),
            'requireNumber' => self::boolean($policy['require_number'] ?? $policy['requireNumber'] ?? false),
            'requireSymbol' => self::boolean($policy['require_symbol'] ?? $policy['requireSymbol'] ?? false),
        ];
    }

    /** @return array<string, list<string>> */
    public static function passwordPolicyErrors(string $password): array
    {
        $policy = self::passwordPolicy();
        $errors = [];

        if (strlen($password) < $policy['minLength']) {
            $errors[] = __('auth.validation.password_min', ['min' => (string) $policy['minLength']]);
        }

        if ($policy['requireUppercase'] && preg_match('/\p{Lu}/u', $password) !== 1) {
            $errors[] = __('auth.validation.password_uppercase');
        }

        if ($policy['requireNumber'] && preg_match('/\d/', $password) !== 1) {
            $errors[] = __('auth.validation.password_number');
        }

        if ($policy['requireSymbol'] && preg_match('/[^\p{L}\p{N}\s]/u', $password) !== 1) {
            $errors[] = __('auth.validation.password_symbol');
        }

        return $errors !== [] ? ['password' => $errors] : [];
    }

    /**
     * Handles the fallback path workflow.
     */
    private static function fallbackPath(string $fallback): string
    {
        $fallback = trim($fallback);
        return $fallback !== '' && str_starts_with($fallback, '/') && !str_starts_with($fallback, '//')
            ? $fallback
            : '/';
    }

    /**
     * Handles the boolean workflow.
     */
    private static function boolean(mixed $value): bool
    {
        if (is_bool($value)) {
            return $value;
        }

        if (is_string($value)) {
            return in_array(strtolower(trim($value)), ['1', 'true', 'yes', 'on'], true);
        }

        return (bool) $value;
    }
}
