<?php

declare(strict_types=1);

/**
 * Catalyst PHP Framework
 *
 * A modern PHP 8.4 framework for building
 * robust and scalable web applications.
 *
 * PHP Version 8.4 (Required).
 *
 * @package    Catalyst
 *
 * @author     Walter Nuñez (arcanisgk/original founder)
 * @email      <wnunez@lh-2.net>
 * @email      <icarosnet@gmail.com>
 * @copyright  2024-2026 Walter Francisco Nuñez Cruz and Icaros Net
 * @license    Proprietary - https://catalyst.lh-2.net/license
 *
 * @version    GIT: See repository tags
 *
 * @category   Framework
 * @filesource
 *
 * @link       https://catalyst.lh-2.net Project homepage
 * @see        https://catalyst.lh-2.net/docs Documentation
 *
 */

namespace Catalyst\Framework\Auth;

use Catalyst\Helpers\Config\ConfigManager;

/**
 * Validates and normalizes public authentication inputs.
 *
 * @package Catalyst\Framework\Auth
 * Responsibility: Guard redirect targets, auth tokens, MFA codes and password-policy checks at auth boundaries.
 */
final class AuthInputGuard
{
    /** Raw email/password tokens are generated by bin2hex(random_bytes(32)). */
    private const RAW_TOKEN_PATTERN = '/\A[a-f0-9]{64}\z/i';

    /** TOTP is 6 digits; backup codes are XXXX-XXXX or XXXXXXXX hexadecimal. */
    private const MFA_CODE_PATTERN = '/\A(?:\d{6}|[A-F0-9]{4}-?[A-F0-9]{4})\z/i';

    /**
     * Return a safe local redirect target. External URLs, protocol-relative URLs,
     * control characters and backslash-based browser ambiguities fall back safely.
     */
    public static function localRedirect(?string $target, string $fallback = '/'): string
    {
        $target = trim((string) $target);
        $fallback = self::fallbackPath($fallback);

        if ($target === '') {
            return $fallback;
        }

        $decoded = rawurldecode($target);

        if (
            $target[0] !== '/'
            || str_starts_with($target, '//')
            || str_contains($target, '\\')
            || str_contains($decoded, '\\')
            || preg_match('/[\x00-\x1F\x7F]/', $target) === 1
            || preg_match('/[\x00-\x1F\x7F]/', $decoded) === 1
            || preg_match('/^[a-z][a-z0-9+.-]*:/i', $decoded) === 1
            || str_starts_with($decoded, '//')
        ) {
            return $fallback;
        }

        return $target;
    }

    /**
     * Checks whether a token matches the expected raw 64-character hex format.
     */
    public static function isRawToken(string $token): bool
    {
        return preg_match(self::RAW_TOKEN_PATTERN, trim($token)) === 1;
    }

    /**
     * Trims and uppercases an MFA code candidate before validation or comparison.
     */
    public static function normalizeMfaCode(string $code): string
    {
        return strtoupper(trim($code));
    }

    /**
     * Checks whether input could be a TOTP code or backup MFA code.
     */
    public static function isMfaCodeCandidate(string $code): bool
    {
        return preg_match(self::MFA_CODE_PATTERN, self::normalizeMfaCode($code)) === 1;
    }

    /**
     * Returns the configured password policy with secure framework defaults.
     *
     * Supported config path:
     * security.security.password_policy = {
     *   "min_length": 12,
     *   "require_uppercase": true,
     *   "require_lowercase": true,
     *   "require_number": true,
     *   "require_symbol": true,
     *   "block_common": true,
     *   "common_passwords": []
     * }
     *
     * @return array{minLength:int,requireUppercase:bool,requireLowercase:bool,requireNumber:bool,requireSymbol:bool,blockCommon:bool,commonPasswords:list<string>}
     */
    public static function passwordPolicy(): array
    {
        $policy = [];

        try {
            $configured = ConfigManager::getInstance()->get('security.security.password_policy', []);
            if (is_array($configured)) {
                $policy = $configured;
            }
        } catch (\Throwable) {
            $policy = [];
        }

        $configuredCommonPasswords = $policy['common_passwords'] ?? $policy['commonPasswords'] ?? [];
        if (!is_array($configuredCommonPasswords)) {
            $configuredCommonPasswords = [];
        }

        return [
            'minLength' => max(8, min(128, (int) ($policy['min_length'] ?? $policy['minLength'] ?? 12))),
            'requireUppercase' => self::boolean($policy['require_uppercase'] ?? $policy['requireUppercase'] ?? true),
            'requireLowercase' => self::boolean($policy['require_lowercase'] ?? $policy['requireLowercase'] ?? true),
            'requireNumber' => self::boolean($policy['require_number'] ?? $policy['requireNumber'] ?? true),
            'requireSymbol' => self::boolean($policy['require_symbol'] ?? $policy['requireSymbol'] ?? true),
            'blockCommon' => self::boolean($policy['block_common'] ?? $policy['blockCommon'] ?? true),
            'commonPasswords' => array_values(array_unique(array_filter(array_map(
                static fn (mixed $value): string => self::normalizePasswordCandidate((string) $value),
                array_merge(self::defaultCommonPasswords(), $configuredCommonPasswords)
            )))),
        ];
    }

    /**
     * Builds translated password-policy validation errors for the supplied password.
     *
     * @return array<string, list<string>>
     */
    public static function passwordPolicyErrors(string $password): array
    {
        $policy = self::passwordPolicy();
        $errors = [];

        if (strlen($password) < $policy['minLength']) {
            $errors[] = __('auth.validation.password_min', ['min' => (string) $policy['minLength']]);
        }

        if ($policy['requireUppercase'] && preg_match('/\p{Lu}/u', $password) !== 1) {
            $errors[] = __('auth.validation.password_uppercase');
        }

        if ($policy['requireLowercase'] && preg_match('/\p{Ll}/u', $password) !== 1) {
            $errors[] = __('auth.validation.password_lowercase');
        }

        if ($policy['requireNumber'] && preg_match('/\d/', $password) !== 1) {
            $errors[] = __('auth.validation.password_number');
        }

        if ($policy['requireSymbol'] && preg_match('/[^\p{L}\p{N}\s]/u', $password) !== 1) {
            $errors[] = __('auth.validation.password_symbol');
        }

        if ($policy['blockCommon'] && in_array(self::normalizePasswordCandidate($password), $policy['commonPasswords'], true)) {
            $errors[] = __('auth.validation.password_common');
        }

        return $errors !== [] ? ['password' => $errors] : [];
    }

    /**
     * Normalizes redirect fallback values to local absolute paths.
     */
    private static function fallbackPath(string $fallback): string
    {
        $fallback = trim($fallback);
        return $fallback !== '' && str_starts_with($fallback, '/') && !str_starts_with($fallback, '//')
            ? $fallback
            : '/';
    }


    /**
     * Returns a compact local denylist for highly common passwords.
     *
     * This is intentionally small to keep the framework self-contained. Projects
     * may append organization-specific values through security.json.
     *
     * Responsibility: Supplies the baseline common-password denylist extended by project configuration.
     * @return list<string>
     */
    private static function defaultCommonPasswords(): array
    {
        return [
            'password',
            'password1',
            'password123',
            '123456',
            '1234567',
            '12345678',
            '123456789',
            '1234567890',
            'qwerty',
            'qwerty123',
            'admin',
            'admin123',
            'administrator',
            'letmein',
            'welcome',
            'welcome1',
            'iloveyou',
            'catalyst',
            'catalyst123',
        ];
    }

    /**
     * Normalizes password candidates for exact denylist comparisons.
     *
     * Responsibility: Produces a stable case-insensitive representation for denylist checks.
     */
    private static function normalizePasswordCandidate(string $value): string
    {
        return strtolower(trim($value));
    }

    /**
     * Converts config-style boolean values into strict booleans.
     */
    private static function boolean(mixed $value): bool
    {
        if (is_bool($value)) {
            return $value;
        }

        if (is_string($value)) {
            return in_array(strtolower(trim($value)), ['1', 'true', 'yes', 'on'], true);
        }

        return (bool) $value;
    }
}
