<aside class="{{ sidebar_class }}">
    <a href="{{ brand_home_href }}" class="logo">
        <span class="logo logo-light">
            <span class="logo-lg"><img src="/assets/vendor/inspinia/images/logo.png" alt="Catalyst"></span>
            <span class="logo-sm"><img src="/assets/vendor/inspinia/images/logo-sm.png" alt="Catalyst"></span>
        </span>
        <span class="logo logo-dark">
            <span class="logo-lg"><img src="/assets/vendor/inspinia/images/logo-black.png" alt="Catalyst"></span>
            <span class="logo-sm"><img src="/assets/vendor/inspinia/images/logo-sm.png" alt="Catalyst"></span>
        </span>
    </a>
    <div class="scrollbar" data-simplebar="" data-simplebar-auto-hide="false">
        <nav id="sidenav-menu" aria-label="{{ sidebar_label }}">
            <ul class="side-nav">
            {{#each navigation_groups}}
                {{> "./_sidebar-node" }}
            {{/each}}
            </ul>
        </nav>
    </div>
</aside>
