<aside class="{{ sidebar_class }}">
    <a href="{{ brand_home_href }}" class="logo">
        <span class="logo logo-light">
            <span class="logo-lg"><img src="{{ brand_logo_dark_url }}" alt="{{ brand_name }}"></span>
            <span class="logo-sm"><img src="{{ brand_logo_small_url }}" alt="{{ brand_name }}"></span>
        </span>
        <span class="logo logo-dark">
            <span class="logo-lg"><img src="{{ brand_logo_light_url }}" alt="{{ brand_name }}"></span>
            <span class="logo-sm"><img src="{{ brand_logo_small_url }}" alt="{{ brand_name }}"></span>
        </span>
    </a>
    <div class="scrollbar" data-simplebar="" data-simplebar-auto-hide="false">
        <nav id="sidenav-menu" aria-label="{{ sidebar_label }}">
            <ul class="side-nav">
            {{#each navigation_groups}}
                {{> "./_sidebar-node" }}
            {{/each}}
            </ul>
        </nav>
    </div>
</aside>
