<!DOCTYPE html>
<html lang="{{ lang }}"
      dir="ltr"
      data-bs-theme="light"
      data-skin="default"
      data-layout-width="fluid"
      data-layout-position="fixed"
      data-menu-color="dark"
      data-sidenav-size="default"
      data-topbar-color="gray">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ document_title }}</title>

    {{#each meta_tags}}
    <meta name="{{ name }}" content="{{ content }}">
    {{/each}}

    {{> "../components/_head-assets" }}

    {{#each style_links}}
    <link href="{{ href }}" rel="{{ rel }}"{{#if has_media}} media="{{ media }}"{{/if}}>
    {{/each}}
</head>
<body>
    {{{ content }}}

    {{> "../components/_body-scripts" }}

    {{#each script_links}}
    <script src="{{ src }}"{{#if has_type}} type="{{ type }}"{{/if}}{{#if defer}} defer{{/if}}{{#if async}} async{{/if}}{{#if has_nonce}} nonce="{{ nonce }}"{{/if}}></script>
    {{/each}}
</body>
</html>
