<?php

declare(strict_types=1);

namespace Catalyst\Framework\Document\Pdf;

final class SimplePdfWriter implements PdfRendererInterface
{
    /**
     * @param array<string, mixed> $watermark
     */
    public function render(string $title, string $body, array $watermark = []): string
    {
        $watermarkImage = $this->loadWatermarkImage($watermark);
        $pages = $this->buildPages($title, $body, $watermark, $watermarkImage);
        $objects = [];

        $fontRegularId = 3;
        $fontBoldId = 4;
        $nextId = 5;
        $watermarkStateId = null;
        $watermarkImageId = null;
        $pageIds = [];

        if ($watermarkImage !== null) {
            $watermarkStateId = $nextId++;
            $watermarkImageId = $nextId++;
        }

        foreach ($pages as $page) {
            $contentId = $nextId++;
            $pageId = $nextId++;
            $pageIds[] = $pageId;

            $stream = $page['stream'];
            $objects[$contentId] = sprintf(
                "<< /Length %d >>\nstream\n%s\nendstream",
                strlen($stream),
                $stream
            );
            $resources = sprintf('/Font << /F1 %d 0 R /F2 %d 0 R >>', $fontRegularId, $fontBoldId);

            if ($watermarkImageId !== null && $watermarkStateId !== null) {
                $resources .= sprintf(' /ExtGState << /GS1 %d 0 R >> /XObject << /Im1 %d 0 R >>', $watermarkStateId, $watermarkImageId);
            }

            $objects[$pageId] = sprintf(
                "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << %s >> /Contents %d 0 R >>",
                $resources,
                $contentId
            );
        }

        $objects[1] = '<< /Type /Catalog /Pages 2 0 R >>';
        $objects[2] = '<< /Type /Pages /Kids [' . implode(' ', array_map(static fn (int $id): string => $id . ' 0 R', $pageIds)) . '] /Count ' . count($pageIds) . ' >>';
        $objects[$fontRegularId] = '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>';
        $objects[$fontBoldId] = '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>';

        if ($watermarkImage !== null && $watermarkStateId !== null && $watermarkImageId !== null) {
            $opacity = max(0.02, min(0.35, (float) ($watermark['logo_opacity'] ?? 0.08)));
            $objects[$watermarkStateId] = sprintf('<< /Type /ExtGState /ca %.3F /CA %.3F >>', $opacity, $opacity);
            $objects[$watermarkImageId] = sprintf(
                "<< /Type /XObject /Subtype /Image /Width %d /Height %d /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length %d >>\nstream\n%s\nendstream",
                (int) $watermarkImage['width'],
                (int) $watermarkImage['height'],
                strlen((string) $watermarkImage['bytes']),
                (string) $watermarkImage['bytes']
            );
        }

        ksort($objects);

        $pdf = "%PDF-1.4\n";
        $offsets = [0];

        foreach ($objects as $id => $object) {
            $offsets[$id] = strlen($pdf);
            $pdf .= $id . " 0 obj\n" . $object . "\nendobj\n";
        }

        $xrefOffset = strlen($pdf);
        $maxId = max(array_keys($objects));
        $pdf .= "xref\n0 " . ($maxId + 1) . "\n";
        $pdf .= "0000000000 65535 f \n";

        for ($id = 1; $id <= $maxId; $id++) {
            $offset = $offsets[$id] ?? 0;
            $pdf .= sprintf("%010d 00000 n \n", $offset);
        }

        $pdf .= "trailer\n";
        $pdf .= "<< /Size " . ($maxId + 1) . " /Root 1 0 R >>\n";
        $pdf .= "startxref\n" . $xrefOffset . "\n%%EOF";

        return $pdf;
    }

    /**
     * @param array<string, mixed> $watermark
     * @param array<string, mixed>|null $watermarkImage
     * @return array<int, array{stream: string}>
     */
    private function buildPages(string $title, string $body, array $watermark, ?array $watermarkImage = null): array
    {
        $marginLeft = 50;
        $marginTop = 786;
        $lineHeight = 16;
        $usableCharacters = 88;
        $lines = [];

        $title = trim($title);
        if ($title !== '') {
            $lines[] = ['font' => 'F2', 'size' => 16, 'text' => $title];
            $lines[] = ['font' => 'F1', 'size' => 10, 'text' => 'Generated by Catalyst document runtime'];
            $lines[] = ['font' => 'F1', 'size' => 10, 'text' => 'Generated at ' . gmdate('Y-m-d H:i:s') . ' UTC'];
            $lines[] = ['font' => 'F1', 'size' => 10, 'text' => ''];
        }

        $bodyLines = preg_split("/\r\n|\r|\n/", $body) ?: [];
        foreach ($bodyLines as $bodyLine) {
            $bodyLine = trim($bodyLine);
            if ($bodyLine === '') {
                $lines[] = ['font' => 'F1', 'size' => 11, 'text' => ''];
                continue;
            }

            foreach ($this->wrapLine($bodyLine, $usableCharacters) as $wrapped) {
                $lines[] = ['font' => 'F1', 'size' => 11, 'text' => $wrapped];
            }
        }

        $linesPerPage = 42;
        $pages = [];
        $chunks = array_chunk($lines, $linesPerPage);

        if ($chunks === []) {
            $chunks = [[]];
        }

        foreach ($chunks as $pageIndex => $chunk) {
            $commands = [];
            $commands[] = '0.18 0.23 0.31 rg';

            if ($watermarkImage !== null) {
                [$drawWidth, $drawHeight, $drawX, $drawY] = $this->watermarkImagePlacement($watermarkImage, $watermark);
                $commands[] = 'q';
                $commands[] = '/GS1 gs';
                $commands[] = sprintf('%.2F 0 0 %.2F %.2F %.2F cm', $drawWidth, $drawHeight, $drawX, $drawY);
                $commands[] = '/Im1 Do';
                $commands[] = 'Q';
            }

            if (!empty($watermark['enabled']) && trim((string) ($watermark['text'] ?? '')) !== '') {
                [$red, $green, $blue] = $this->hexToRgbFraction((string) ($watermark['color'] ?? '#CBD5E1'));
                $fontSize = max(24, min(96, (int) ($watermark['font_size'] ?? 46)));
                $commands[] = 'BT';
                $commands[] = sprintf('%.3F %.3F %.3F rg', $red, $green, $blue);
                $commands[] = sprintf('/F2 %d Tf', $fontSize);
                $commands[] = '110 420 Td';
                $commands[] = '(' . $this->escapeText(trim((string) $watermark['text'])) . ') Tj';
                $commands[] = 'ET';
                $commands[] = '0.18 0.23 0.31 rg';
            }

            $commands[] = 'BT';
            $currentY = $marginTop;
            foreach ($chunk as $index => $line) {
                if ($index === 0) {
                    $commands[] = sprintf('/%s %d Tf', $line['font'], (int) $line['size']);
                    $commands[] = sprintf('%d %d Td', $marginLeft, $currentY);
                } else {
                    $commands[] = sprintf('0 -%d Td', $lineHeight);
                    $commands[] = sprintf('/%s %d Tf', $line['font'], (int) $line['size']);
                }

                $commands[] = '(' . $this->escapeText((string) $line['text']) . ') Tj';
            }

            if ($chunk === []) {
                $commands[] = '/F1 11 Tf';
                $commands[] = sprintf('%d %d Td', $marginLeft, $currentY);
                $commands[] = '( ) Tj';
            }

            $commands[] = 'ET';
            $commands[] = 'BT';
            $commands[] = '/F1 9 Tf';
            $commands[] = '495 20 Td';
            $commands[] = '(' . $this->escapeText(sprintf('Page %d/%d', $pageIndex + 1, count($chunks))) . ') Tj';
            $commands[] = 'ET';

            $pages[] = [
                'stream' => implode("\n", $commands),
            ];
        }

        return $pages;
    }

    /**
     * @return array<int, string>
     */
    private function wrapLine(string $line, int $width): array
    {
        $wrapped = wordwrap($line, $width, "\n", true);

        return preg_split("/\r\n|\r|\n/", $wrapped) ?: [$line];
    }

    private function escapeText(string $text): string
    {
        $text = str_replace('\\', '\\\\', $text);
        $text = str_replace('(', '\(', $text);
        $text = str_replace(')', '\)', $text);

        return preg_replace('/[^\x20-\x7E]/', '?', $text) ?? '';
    }

    /**
     * @return array{0: float, 1: float, 2: float}
     */
    private function hexToRgbFraction(string $hex): array
    {
        $hex = strtoupper(trim($hex));
        if (preg_match('/^#[0-9A-F]{6}$/', $hex) !== 1) {
            $hex = '#CBD5E1';
        }

        return [
            hexdec(substr($hex, 1, 2)) / 255,
            hexdec(substr($hex, 3, 2)) / 255,
            hexdec(substr($hex, 5, 2)) / 255,
        ];
    }

    /**
     * @param array<string, mixed> $watermark
     * @return array{bytes: string, width: int, height: int}|null
     */
    private function loadWatermarkImage(array $watermark): ?array
    {
        $path = trim((string) ($watermark['logo_path'] ?? ''));
        if ($path === '' || !is_file($path)) {
            return null;
        }

        $bytes = @file_get_contents($path);
        if ($bytes === false || $bytes === '') {
            return null;
        }

        $imageInfo = @getimagesizefromstring($bytes);
        if ($imageInfo === false) {
            return null;
        }

        $mime = strtolower((string) ($imageInfo['mime'] ?? ''));
        if (!in_array($mime, ['image/jpeg', 'image/jpg'], true)) {
            return null;
        }

        return [
            'bytes' => $bytes,
            'width' => (int) ($imageInfo[0] ?? 0),
            'height' => (int) ($imageInfo[1] ?? 0),
        ];
    }

    /**
     * @param array<string, mixed> $image
     * @param array<string, mixed> $watermark
     * @return array{0: float, 1: float, 2: float, 3: float}
     */
    private function watermarkImagePlacement(array $image, array $watermark): array
    {
        $pageWidth = 595.0;
        $pageHeight = 842.0;
        $sourceWidth = max(1.0, (float) ($image['width'] ?? 1));
        $sourceHeight = max(1.0, (float) ($image['height'] ?? 1));
        $maxWidth = max(160.0, min(340.0, (float) ($watermark['logo_max_width'] ?? 280)));
        $maxHeight = 220.0;
        $scale = min($maxWidth / $sourceWidth, $maxHeight / $sourceHeight, 1.0);
        $drawWidth = round($sourceWidth * $scale, 2);
        $drawHeight = round($sourceHeight * $scale, 2);
        $drawX = round(($pageWidth - $drawWidth) / 2, 2);
        $drawY = round(max(140.0, (($pageHeight - $drawHeight) / 2) - 40.0), 2);

        return [$drawWidth, $drawHeight, $drawX, $drawY];
    }
}
